In [13]:
#imports
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif, mutual_info_classif
from sklearn.feature_selection import SequentialFeatureSelector

sample = pd.read_csv("../../data/processed/sample.csv", sep="|")
sample.head()

,lineID,day,pid,adFlag,availability,competitorPrice,click,basket,order,price,...,genericProduct,salesIndex,category,rrp,campaignIndex_A,campaignIndex_B,campaignIndex_C,price_diff_competitor,price_ratio_competitor,price_pct_diff_competitor
0,978899,39,9624,0,1,17.19,1,0,0,19.89,...,0,40,17.0,21.51,0,0,0,2.70,1.16,15.71
1,1267035,47,3969,1,1,18.13,1,0,0,20.85,...,0,40,9.0,26.07,0,0,0,2.72,1.15,15.00
2,297914,14,16633,0,1,15.06,0,0,1,16.45,...,0,40,132.0,23.98,0,1,0,1.39,1.09,9.23
3,2554963,87,20147,0,1,4.36,1,0,0,5.17,...,0,53,28.0,5.45,0,0,0,0.81,1.19,18.58
4,2739211,92,14326,0,1,6.12,0,0,1,6.22,...,0,53,3.0,6.55,0,0,0,0.10,1.02,1.63

In [14]:
#target variable
y = sample["order"]

#drop unnessacary tables:
x = sample.drop(columns=["order", "lineID", "revenue", "click", "basket"])
x.head()

,day,pid,adFlag,availability,competitorPrice,price,manufacturer,group,content,unit,...,genericProduct,salesIndex,category,rrp,campaignIndex_A,campaignIndex_B,campaignIndex_C,price_diff_competitor,price_ratio_competitor,price_pct_diff_competitor
0,39,9624,0,1,17.19,19.89,17,2FOI,30,ML,...,0,40,17.0,21.51,0,0,0,2.70,1.16,15.71
1,47,3969,1,1,18.13,20.85,556,19OS28,80,ST,...,0,40,9.0,26.07,0,0,0,2.72,1.15,15.00
2,14,16633,0,1,15.06,16.45,168,1COSF,50,ST,...,0,40,132.0,23.98,0,1,0,1.39,1.09,9.23
3,87,20147,0,1,4.36,5.17,101,21OKG,30,ST,...,0,53,28.0,5.45,0,0,0,0.81,1.19,18.58
4,92,14326,0,1,6.12,6.22,119,21OKG,120,ST,...,0,53,3.0,6.55,0,0,0,0.10,1.02,1.63

Univariate (each feature alone)

In [15]:
inf = sample[sample["price_ratio_competitor"].eq(np.inf)]
inf = inf.filter(items=["price", "competitorPrice", "price_diff_competitor", 'price_ratio_competitor', "price_pct_diff_competitor"])
inf.head(76)

Empty DataFrame
Columns: [price, competitorPrice, price_diff_competitor, price_ratio_competitor, price_pct_diff_competitor]
Index: []

In [16]:
df = pd.read_csv("../../data/processed/processed_joined_dataset.csv", sep="|")
line2253839 = df[df["lineID"] == 2253839]
line2253839.head()

,lineID,day,pid,adFlag,availability,competitorPrice,click,basket,order,price,...,genericProduct,salesIndex,category,rrp,campaignIndex_A,campaignIndex_B,campaignIndex_C,price_diff_competitor,price_ratio_competitor,price_pct_diff_competitor
2253662,2253839,77,13461,0,1,5.91,1,0,0,6.0,...,1,40,5.0,9.37,0,0,0,0.09,1.02,1.52