In [7]:
# Standard library
import warnings
from operator import truediv
from pathlib import Path

# Data manipulation
import numpy as np
import pandas as pd

ITEMS_DATA_PATH = "../../data/raw/items.csv"
TRAIN_DATA_PATH = "../../data/raw/train.csv"

In [5]:
items = pd.read_csv(ITEMS_DATA_PATH, sep="|")
items.sample(10, random_state=42)

,pid,manufacturer,group,content,unit,pharmForm,genericProduct,salesIndex,category,campaignIndex,rrp
18221,18222,219,22OH,50,ML,CRE,0,53,NaN,NaN,13.14
13358,13359,97,14OH2FOZ,120,ST,WKA,0,40,100.0,NaN,60.40
9511,9512,101,21OK3,45,ST,TAB,0,53,350.0,NaN,4.35
17571,17572,534,1EOH20OZ,50,ST,TTR,0,53,99.0,NaN,27.45
13871,13872,82,19OJ3FOZ,60,ST,FTA,0,40,163.0,NaN,17.27
3393,3394,90,20OI0,25X2,ST,KOM,0,53,14.0,NaN,8.13
9214,9215,90,13OX0FOS,250,ML,LOE,0,52,127.0,NaN,10.64
4397,4398,1,2FOI,10,G,GLO,0,40,309.0,NaN,9.85
812,813,95,20OIF,10,ST,Ver,0,53,NaN,NaN,47.32
18029,18030,101,21OKG,60,ST,KAP,0,53,27.0,NaN,31.85

In [11]:
items.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 22035 entries, 0 to 22034
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   pid             22035 non-null  int64
 1   manufacturer    22035 non-null  int64
 2   group           22035 non-null  str
 3   content         22035 non-null  str
 4   unit            22035 non-null  str
 5   pharmForm       19708 non-null  str
 6   genericProduct  22035 non-null  int64
 7   salesIndex      22035 non-null  int64
 8   category        17408 non-null  float64
 9   campaignIndex   1338 non-null   str
 10  rrp             22035 non-null  float64
dtypes: float64(2), int64(4), str(5)
memory usage: 1.8 MB

In [12]:
items.nunique()

pid               22035
manufacturer       1067
group               533
content             548
unit                  8
pharmForm           278
genericProduct        2
salesIndex            4
category            409
campaignIndex         3
rrp                3289
dtype: int64

In [18]:
#checking if pid has duplicate
items_duplicate_pid = items["pid"].duplicated().sum()
print(f"items_duplicate_pid: {items_duplicate_pid}")

#checking for 0 and NA
items_missing_pid = items["pid"].isna().sum()
print(f"items_missing_pid: {items_missing_pid}")

#number of uniques
items_unique_pid = items["pid"].nunique()
print(f"items_unique_pid: {items_unique_pid}")

items_duplicate_pid: 0
items_missing_pid: 0
items_unique_pid: 22035

In [23]:
#checking if pid has duplicate
items_size_manufacturer = items["manufacturer"].size
print(f"items_size_manufacturer: {items_size_manufacturer}")

#checking unique values
items_unique_manufacturer = items["manufacturer"].nunique()
print(f"items_unique_manufacturer: {items_unique_manufacturer}")

#check for missing values
items_missing_manufacturer = items["manufacturer"].isna().sum()
print(f"items_missing_manufacturer: {items_missing_manufacturer}")

items_size_manufacturer: 22035
items_unique_manufacturer: 1067
items_missing_manufacturer: 0

In [6]:
train = pd.read_csv(TRAIN_DATA_PATH, sep="|")
train.sample(10, random_state=42)

,lineID,day,pid,adFlag,availability,competitorPrice,click,basket,order,price,revenue
309086,309087,14,4369,0,1,6.48,0,1,0,9.11,0.00
1073951,1073952,41,12825,0,2,10.73,0,1,0,13.02,0.00
2705599,2705600,91,2365,1,1,22.87,0,1,0,25.25,0.00
432442,432443,21,8415,1,1,16.09,1,0,0,16.45,0.00
97520,97521,5,3231,0,1,5.38,1,0,0,6.06,0.00
458664,458665,22,13307,0,1,17.51,1,0,0,20.25,0.00
2324611,2324612,80,9252,1,1,7.36,0,0,1,7.65,7.65
219992,219993,11,5780,0,1,15.94,0,1,0,18.51,0.00
117310,117311,6,16410,0,1,8.42,0,1,0,8.57,0.00
1925682,1925683,67,10027,1,1,19.22,0,0,1,24.14,24.14

In [9]:
train.info(show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 2756003 entries, 0 to 2756002
Data columns (total 11 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   lineID           2756003 non-null  int64
 1   day              2756003 non-null  int64
 2   pid              2756003 non-null  int64
 3   adFlag           2756003 non-null  int64
 4   availability     2756003 non-null  int64
 5   competitorPrice  2655316 non-null  float64
 6   click            2756003 non-null  int64
 7   basket           2756003 non-null  int64
 8   order            2756003 non-null  int64
 9   price            2756003 non-null  float64
 10  revenue          2756003 non-null  float64
dtypes: float64(3), int64(8)
memory usage: 231.3 MB

In [10]:
train.nunique()

lineID             2756003
day                     92
pid                  21928
adFlag                   2
availability             4
competitorPrice       4992
click                    2
basket                   2
order                    2
price                 7475
revenue               7520
dtype: int64